#!/usr/bin/env bash
# build.sh — Build the wolfCrypt/OpenSSL shim from a clean checkout.
#
# Usage:
#   ./build.sh           # full build
#   ./build.sh wolfssl   # rebuild wolfSSL only
#   ./build.sh shim      # rebuild shim only
#   ./build.sh openssl   # rebuild OpenSSL only
#
# Prerequisites (Debian/Ubuntu):
#   sudo apt install build-essential autoconf automake libtool

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
NPROC=$(nproc 2>/dev/null || sysctl -n hw.logicalcpu 2>/dev/null || echo 4)
TARGET="${1:-all}"

# ── Step 0: submodules ───────────────────────────────────────────────────────
init_submodules() {
    info "Initialising submodules..."
    git -C "$ROOT" submodule update --init --depth=1
    ok "openssl/ and wolfssl/ checked out"
}

info()  { printf '\033[1;34m[build]\033[0m %s\n' "$*"; }
ok()    { printf '\033[1;32m[build]\033[0m %s\n' "$*"; }
die()   { printf '\033[1;31m[build]\033[0m ERROR: %s\n' "$*" >&2; exit 1; }

# ── Step 1: wolfSSL ──────────────────────────────────────────────────────────
build_wolfssl() {
    info "Building wolfSSL v5.9.0-stable..."
    [ -f "$ROOT/wolfssl/configure.ac" ] || init_submodules
    cd "$ROOT/wolfssl"

    [ -f configure ] || {
        info "Running autogen.sh..."
        ./autogen.sh
    }

    ./configure \
        --enable-opensslall    \
        --enable-opensslextra  \
        --enable-des3          \
        --enable-arc4          \
        --enable-md4           \
        --enable-ripemd        \
        --enable-dsa           \
        --enable-rsa           \
        --enable-ecc           \
        --enable-aesctr        \
        --enable-aescfb        \
        --enable-keygen        \
        --enable-debug         \
        --enable-sha3          \
        --enable-shake128      \
        --enable-shake256      \
        CFLAGS="-DOPENSSL_EXTRA"

    make -j"$NPROC"
    ok "wolfSSL built → wolfssl/src/.libs/libwolfssl.so"
    cd "$ROOT"
}

# ── Step 2: shim ─────────────────────────────────────────────────────────────
build_shim() {
    info "Building wolfshim..."
    cd "$ROOT"
    mkdir -p shim/lib

    [ -f wolfssl/src/.libs/libwolfssl.so ] || \
        die "libwolfssl.so not found — run './build.sh wolfssl' first"

    WOLF_CFLAGS=(
        -O2 -Wall
        -I"$ROOT/wolfssl"
        -I"$ROOT/shim/include"
        -I"$ROOT/openssl"
        -I"$ROOT/openssl/include"
    )

    SHIM_SRCS=(
        shim/src/wolfshim_abi_check.c
        shim/src/sha/sha_shim.c
        shim/src/aesni/aesni_shim.c
        shim/src/aliases/aliases.c
        shim/src/stubs/misc_stubs.c
        shim/src/pkey/pkey_meth_shim.c
        shim/src/evp/evp_wolf_bridge.c
        shim/src/evp/evp_digest_shim.c
        shim/src/rand/rand_shim.c
        shim/src/aes/aes_shim.c
        shim/src/des/des_shim.c
        shim/src/des/des_modes_bridge.c
        shim/src/chacha/chacha_shim.c
        shim/src/rc4/rc4_shim.c
        shim/src/legacy_stubs/legacy_cipher_stubs.c
    )

    SHIM_OBJS=()
    for src in "${SHIM_SRCS[@]}"; do
        obj="${src%.c}.o"
        info "  cc $src"
        gcc "${WOLF_CFLAGS[@]}" -c "$src" -o "$obj"
        SHIM_OBJS+=("$obj")
    done

    rm -f shim/lib/libwolfshim.a
    ar rcs shim/lib/libwolfshim.a "${SHIM_OBJS[@]}" \
        openssl/crypto/siphash/siphash.o \
        openssl/crypto/siphash/siphash_ameth.o \
        openssl/crypto/siphash/siphash_pmeth.o \
        openssl/crypto/poly1305/poly1305_ameth.o \
        openssl/crypto/poly1305/poly1305_pmeth.o
    ok "shim/lib/libwolfshim.a built (${#SHIM_OBJS[@]} objects)"
}

# ── Step 3: OpenSSL ───────────────────────────────────────────────────────────
build_openssl() {
    info "Building OpenSSL 1.1.1w (WOLFCRYPT_EXCLUDE=1)..."
    [ -f "$ROOT/openssl/Configure" ] || init_submodules
    cd "$ROOT/openssl"

    # Apply our patches to the submodule working tree (idempotent via patch -N)
    patch -N -p1 < "$ROOT/patches/openssl-wolfshim.patch" 2>/dev/null || true

    # The Makefile is generated by ./Configure then modified for WOLFCRYPT_EXCLUDE.
    # We keep the pre-modified version in the repo and copy it in.
    if [ ! -f Makefile ] || ! grep -q WOLFCRYPT_EXCLUDE Makefile; then
        info "Installing wolfshim Makefile..."
        cp "$ROOT/patches/Makefile.wolfshim" Makefile
    fi

    [ -f "$ROOT/wolfssl/src/.libs/libwolfssl.so" ] || \
        die "libwolfssl.so not found — run './build.sh wolfssl' first"
    [ -f "$ROOT/shim/lib/libwolfshim.a" ] || \
        die "libwolfshim.a not found — run './build.sh shim' first"

    # WOLFCRYPT_EXCLUDE=1 is mandatory: omits OpenSSL's AES/SHA/RAND objects so
    # the shim's wolfCrypt-backed implementations are used instead.  Setting it
    # to 0 re-enables BSAES assembly, which reads AES_KEY.rd_key[] as a round-key
    # schedule; the shim stores a wolfCrypt pointer there and BSAES would silently
    # produce wrong ciphertext.  Always pass this flag explicitly.
    make WOLFCRYPT_EXCLUDE=1 -j"$NPROC"
    ok "OpenSSL built"
    ok "  libcrypto.so.1.1  libssl.so.1.1  apps/openssl"
    cd "$ROOT"
}

# ── Dispatch ─────────────────────────────────────────────────────────────────
case "$TARGET" in
    wolfssl) build_wolfssl ;;
    shim)    build_shim    ;;
    openssl) build_openssl ;;
    all)
        init_submodules
        build_wolfssl
        build_shim
        build_openssl
        echo ""
        ok "=== Build complete ==="
        echo ""
        echo "Test with:"
        echo "  cd openssl"
        echo "  export LD_LIBRARY_PATH=.:../wolfssl/src/.libs"
        echo "  ./apps/openssl version"
        echo "  ./apps/openssl dgst -sha256 /dev/null"
        ;;
    *)
        die "Unknown target '$TARGET'. Use: wolfssl | shim | openssl | all"
        ;;
esac
